import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

/**
 * Interface extending jsPDF to include autoTable method from the plugin
 */
interface jsPDFWithPlugin extends jsPDF {
    autoTable: (options: any) => jsPDF;
}

export interface ExportColumnData {
    header: string;
    dataKey: string;
}

/**
 * Downloads data as a CSV file.
 * @param data Array of objects representing rows.
 * @param filename Name of the file to be downloaded (without .csv extension).
 */
export const exportToCSV = (data: Record<string, any>[], filename: string) => {
    if (!data || data.length === 0) {
        console.warn("No data provided for CSV export.");
        return;
    }

    // Extract headers
    const headers = Object.keys(data[0]);
    const csvRows = [];

    // Add header row
    csvRows.push(headers.join(','));

    // Add data rows
    for (const row of data) {
        const values = headers.map(header => {
            const val = row[header] !== undefined && row[header] !== null ? row[header] : '';
            const stringVal = String(val);
            // Escape quotes and wrap in quotes if contains comma
            const escaped = stringVal.replace(/"/g, '""');
            return stringVal.includes(',') ? `"${escaped}"` : stringVal;
        });
        csvRows.push(values.join(','));
    }

    const csvString = csvRows.join('\n');
    const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });

    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    link.setAttribute('href', url);
    link.setAttribute('download', `${filename}-${format(new Date(), 'yyyy-MM-dd')}.csv`);
    link.style.visibility = 'hidden';

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};

export interface DashboardExportData {
    revenue: number;
    cashTotal: number;
    cardTotal: number;
    discounts: number;
    totalOffers: number;
    totalComplimentary: number;
    grossRevenue: number;
    ordersCount: number;
    aov: number;
    topProducts: { name: string; quantity: number }[];
    dateRangeLabel: string;
    adminName: string;
}

/**
 * Generates and downloads a specialized PDF End of Day Summary for the Dashboard.
 */
export const exportDashboardToPDF = (data: DashboardExportData) => {
    const doc = new jsPDF() as jsPDFWithPlugin;

    // Coko Branding / Header
    doc.setFontSize(22);
    doc.setTextColor(112, 0, 255); // A nice purple
    doc.text("Coko POS", 14, 20);

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Business Summary Report", 14, 30);

    // Meta Info
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${format(new Date(), 'MMM dd, yyyy HH:mm')}`, 14, 40);
    doc.text(`Period: ${data.dateRangeLabel}`, 14, 45);
    doc.text(`Generated By: ${data.adminName}`, 14, 50);

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 55, 196, 55);

    // Financial Summary Section
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Financial Overview", 14, 65);

    const formatCurrency = (amount: number) => `Nrs. ${amount.toLocaleString()}`;

    // Use autoTable for layout of summary metrics
    doc.autoTable({
        startY: 70,
        head: [['Metric', 'Value']],
        body: [
            ['Gross Sales', formatCurrency(data.grossRevenue)],
            ['Promo Offers (Gifts)', formatCurrency(data.totalOffers)],
            ['Complimentary Items', formatCurrency(data.totalComplimentary)],
            ['Discounts Provided', formatCurrency(data.discounts)],
            ['Net Revenue', formatCurrency(data.revenue)],
            ['---', '---'],
            ['Total Orders', data.ordersCount.toString()],
            ['Avg. Order Value', formatCurrency(data.aov)],
            ['Cash Collected', formatCurrency(data.cashTotal)],
            ['Card/Fonepay Collected', formatCurrency(data.cardTotal)],
        ],
        theme: 'grid',
        headStyles: { fillColor: [240, 240, 245], textColor: 0, fontStyle: 'bold' },
        columnStyles: {
            0: { cellWidth: 100, fontStyle: 'bold' },
            1: { cellWidth: 'auto', halign: 'right' }
        },
        margin: { left: 14 }
    });

    // Top Products Section
    const finalY = (doc as any).lastAutoTable.finalY || 70;

    if (data.topProducts && data.topProducts.length > 0) {
        doc.setFontSize(14);
        doc.text("Top Selling Products", 14, finalY + 15);

        doc.autoTable({
            startY: finalY + 20,
            head: [['Product Name', 'Quantity Sold']],
            body: data.topProducts.map(p => [p.name, p.quantity.toString()]),
            theme: 'striped',
            headStyles: { fillColor: [112, 0, 255], textColor: 255 },
            columnStyles: {
                0: { cellWidth: 'auto' },
                1: { cellWidth: 50, halign: 'center' }
            },
            margin: { left: 14 }
        });
    }

    // Footer
    const pageCount = (doc.internal as any).getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `Page ${i} of ${pageCount}`,
            doc.internal.pageSize.getWidth() / 2,
            doc.internal.pageSize.getHeight() - 10,
            { align: 'center' }
        );
    }

    // Download the PDF
    doc.save(`dashboard-summary-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
};
